<a href="https://colab.research.google.com/github/DSF-Kotaro/blog/blob/main/%E3%80%90%E7%AC%AC%EF%BC%95%E5%9B%9E%E3%80%91%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9%EF%BC%88Numpy%EF%BC%89.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpyのインポート（Import numpy）

In [1]:
import numpy as np

##配列操作（Array manipulation）

###配列（Array）

In [3]:
data = np.array([5,2,6,4,10,0,7,8,1,5])
data

array([ 5,  2,  6,  4, 10,  0,  7,  8,  1,  5])

###データの型（Types of datas）

In [4]:
data.dtype

dtype('int64')

###次元数と要素数（Number of dimensions and number of elements）

In [5]:
print('Number of dimensions:',data.ndim)
print('Number of elements:',data.size)

Number of dimensions: 1
Number of elements: 10


###全ての要素に対する計算（Calculation for all elements）

In [6]:
data

array([ 5,  2,  6,  4, 10,  0,  7,  8,  1,  5])

In [7]:
data * 2

array([10,  4, 12,  8, 20,  0, 14, 16,  2, 10])

In [8]:
data - 2

array([ 3,  0,  4,  2,  8, -2,  5,  6, -1,  3])

In [9]:
data / 2

array([2.5, 1. , 3. , 2. , 5. , 0. , 3.5, 4. , 0.5, 2.5])

In [12]:
data=data / 2
data.dtype

dtype('float64')

###並べ替え（Sort）

In [14]:
data = np.array([5,2,6,4,10,0,7,8,1,5])
data

array([ 5,  2,  6,  4, 10,  0,  7,  8,  1,  5])

In [16]:
data.sort()
data

array([ 0,  1,  2,  4,  5,  5,  6,  7,  8, 10])

In [22]:
data[::-1].sort()
data

array([10,  8,  7,  6,  5,  5,  4,  2,  1,  0])

###最小・最大・合計・積上の計算（Minimum / maximum / total / product calculation）

In [23]:
data.min()

0

In [24]:
data.max()

10

In [25]:
data.sum()

48

In [26]:
data.cumsum()

array([10, 18, 25, 31, 36, 41, 45, 47, 48, 48])

In [27]:
data.cumsum()/data.sum()

array([0.20833333, 0.375     , 0.52083333, 0.64583333, 0.75      ,
       0.85416667, 0.9375    , 0.97916667, 1.        , 1.        ])

###乱数（random number）

In [28]:
import numpy.random as random

In [29]:
random.seed(0)

In [31]:
rnd_data = random.rand(10)
rnd_data

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

###データのランダムな抽出（Random extraction of data）

In [32]:
data = np.array([9,2,3,4,10,6,7,8,1,5])

random.choice(data,10)

array([3, 4, 1, 2, 4, 4, 4, 8, 9, 2])

In [33]:
data = np.array([9,2,3,4,10,6,7,8,1,5])

random.choice(data,10,replace = False)

array([ 1,  2,  6,  7,  4, 10,  3,  8,  9,  5])

##行列（queue）

In [35]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
array1 = np.arange(9).reshape(3,3)
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
array1[0,:]

array([0, 1, 2])

In [38]:
array1[1,:]

array([3, 4, 5])

In [39]:
array1[:,2]

array([2, 5, 8])

##行列の演算（Matrix operation）

In [40]:
array2 = np.arange(9,18).reshape(3,3)
array2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [41]:
np.dot(array1,array2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [42]:
array1 * array2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

##要素が0や１の行列を作る（Create a matrix with 0 or 1 elements）

In [43]:
np.zeros((2,3),dtype = np.int64)

array([[0, 0, 0],
       [0, 0, 0]])

In [44]:
np.ones((2,3), dtype = np.float64)

array([[1., 1., 1.],
       [1., 1., 1.]])